### ISSUE TITLE
Error reading multiple ITK images

### ISSUE THREAD

**Issue by floryst** [Kitware/pv-web-viewer#58]
To reproduce:

1. Have a large image file readable by itk.js. I generated a 100x100x100 wavelet using paraview and exported it to NRRD.
1. Open image file in glance
1. Delete the image dataset from the pipeline editor
1. Open the image again

Console outputs an uncaught promise error object:
```
{
  "message":"parameter 0 has unknown type emsc",
  "stack":"BindingError: parameter 0 has unknown type emsc
               at BindingError.<anonymous> (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:107142)
               at new BindingError (eval at createNamedFunction (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:106848), <anonymous>:4:34)
               at throwBindingError (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:107587)
               at requireRegisteredType (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:134433)
               at emval_allocator_1 (eval at craftEmvalAllocator (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:143459), <anonymous>:4:16)
               at __emval_new (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:143803)
               at wasm-function[1550]:18\n    at invoke_iiiii (http://localhost:9999/itk/ImageIOs/itkNrrdImageIOJSBindingWasm.js:1:159365)
               at wasm-function[139]:4495\n    at wasm-function[175]:73"
}
```

@thewtex do you know anything about this error message?

**Comment by thewtex** [comment]
@floryst I have not seen this before, but we can work around the issue with these changes:

  https://github.com/InsightSoftwareConsortium/itk-js/pull/121

i.e. call `terminate()` on the web worker, and force the generation of a new one on the second invocation.

**Comment by floryst** [comment]
Relevant fix: https://github.com/Kitware/vtk-js/pull/711
